#!/bin/bash
# ===========================================
# CLOUD SHELL SETUP SCRIPT
# Execute ESTES COMANDOS MANUALMENTE no Cloud Shell
# ===========================================

echo "🚀 CLOUD SHELL SETUP - EXECUTE ESTES COMANDOS:"
echo "=============================================="
echo ""
echo "1. PRIMEIRO, FAÇA LOGIN COM SUA CONTA PESSOAL:"
echo "----------------------------------------------"
echo "gcloud auth login"
echo "# Isso abrirá uma janela no browser para login"
echo ""
echo "2. DEPOIS, CONFIGURE O PROJETO:"
echo "--------------------------------"
echo "gcloud config set project project-7be1cae5-5f08-45fb-aca"
echo ""
echo "3. AGORA FAÇA O DEPLOY MANUAL:"
echo "-------------------------------"
echo "cd /home/originslone/crypto-asteroid-rush"
echo "./deploy-manual.sh"
echo ""
echo "4. SE O DEPLOY FUNCIONAR, CONFIGURE O AUTOMÁTICO:"
echo "--------------------------------------------------"
echo "# Acesse o Console Web:"
echo "# 1. https://console.cloud.google.com/cloud-build"
echo "# 2. Clique em 'Triggers'"
echo "# 3. Crie trigger com cloudbuild-simple.yaml"
echo ""
echo "5. TESTE O DEPLOY AUTOMÁTICO:"
echo "------------------------------"
echo "git commit --allow-empty -m 'Teste deploy automático'"
echo "git push origin main"
echo ""
echo "📋 MONITORAMENTO:"
echo "-----------------"
echo "- Cloud Build: https://console.cloud.google.com/cloud-build"
echo "- Cloud Run: https://console.cloud.google.com/run"
echo "- Logs: https://console.cloud.google.com/logs"
echo ""
echo "🔧 SE TIVER ERROS DE PERMISSÃO:"
echo "--------------------------------"
echo "# Acesse IAM: https://console.cloud.google.com/iam-admin/iam"
echo "# Adicione estas roles à service account do Cloud Build:"
echo "# 1. Cloud Run Admin"
echo "# 2. Service Account User"
echo "# 3. Cloud Build Service Account"
echo "# 4. Cloud SQL Client"
echo ""
echo "🎉 PRONTO! Execute o passo 1 agora no Cloud Shell."